language: php

php:
  - 5.6

services:
  - mysql

before_script:
    - mysql -e 'create database rainbow;'
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --no-interaction --prefer-source
    - app/console cache:warmup --env=test --quiet

script:
  - app/console doctrine:schema:update --force
  - app/console doctrine:fixtures:load --fixtures=src/AppBundle/DataFixtures/ORM/Dev --append --purge-with-truncate
  - phpunit -c app/ --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover