hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login-social

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

vkontakte_login:
    path: /login/check-vkontakte

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: %app_locales%
    defaults:
        _locale: %locale%

homepage:
    path:      /{_locale}
    defaults:  { _controller: AppBundle:Site:index, _locale: ru }
    requirements:
        _locale:  ru|en

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"